### ISSUE TITLE
GitRunners is shutting down

### ISSUE THREAD

**Issue by Piedone** [neysofu/awesome-github-actions-runners#16]
FYI, so I think they can be removed.

**Comment by neysofu** [comment]
Thanks for the heads up. Where can I find some official information about this?

**Comment by Piedone** [comment]
Every user got an e-mail, I don't know if there's any public info about this.

**Comment by neysofu** [comment]
Thank you, appreciated. I'll write a PR.

**Comment by neysofu** [comment]
Done.
