### ISSUE TITLE
blacksmith.sh

### ISSUE THREAD

**Issue by neysofu** [neysofu/awesome-github-actions-runners#20]
https://blacksmith.sh/

**Comment by crohr** [comment]
How many GHA provider companies will YC fund? :D

They are hosted at Hetzner, same as Buildjet and Ubicloud.

**Comment by neysofu** [comment]
Too many... but it's a winner-takes-all kind of market, so lower quality providers will exit the race pretty soon, is my guess.

**Comment by crohr** [comment]
Or until Hetzner runs out of gaming CPUs

**Comment by crohr** [comment]
To be fair to Buildjet and Blacksmith, when you do end up on the high-end CPU runners, they are the fastest (for purely CPU-constraint builds like this nodejs example)

<img width="607" alt="image" src="https://github.com/neysofu/awesome-github-actions-runners/assets/6114/a2aa2e22-4576-484c-8285-d3df6716f63c">

**Comment by neysofu** [comment]
Yeah, but my team consistently has to wait around 20secs-5mins for Buildjet runners with 8+ cores. It's not very nice. That's one one of the main reasons why I put them lower on the list a while ago; the experience is decent but they refuse to do anything about the bandwidth situation and runner availability.

**Comment by crohr** [comment]
Another run showing the random part of getting a fast runner at buildjet. Also using RunsOn with twice the CPU count to get ahead everyone else, and still cheaper.

<img width="605" alt="image" src="https://github.com/neysofu/awesome-github-actions-runners/assets/6114/3c87c851-4d2a-4b8b-a21b-8172bf59fa14">

**Comment by adijp** [comment]
@neysofu Hey Filippo, I'm one of the founders of blacksmith.sh. We love this list you're maintaining, and would love to be a part of it. I created a PR here https://github.com/neysofu/awesome-github-actions-runners/pull/21. Thanks!

**Comment by neysofu** [comment]
Thanks for the PR @adijp! I've responded to the PR with some suggestions. 💪
